name: resident
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: 0.8.2+3
  firebase_core: 0.2.5+1
  firebase_auth: 0.7.0
  firebase_storage: 1.0.4
  firebase_messaging: 2.1.0
  firebase_analytics: 1.1.0
#  firebase_admob: 0.7.0
  path_provider: 0.4.1
  flutter_masked_text: ^0.7.0
  shared_preferences: 0.4.3
  cached_network_image: 0.5.1
  intl: ^0.15.7
  universal_widget: ^1.2.5
  image_picker: 0.4.12+1
  device_info: ^0.4.0+1
  font_awesome_flutter: ^8.4.0
  flutter_sound: 1.2.1
  audioplayers: ^0.8.0
  # file_picker: ^1.3.4+1
  open_file: 1.3.0
#  flutter_record: ^0.3.1
#  rich_alert 0.1.32
#  flutter_backdrop: ^1.0.3
#  card_settings: ^1.4.1
#  contacts_service: ^0.2.1
#  progress_indicators: ^0.1.2
#  animated_text_kit: ^1.3.0
#  keyboard_visibility: ^0.5.1
#  folding_cell: ^0.1.1
#  polygon_clipper: ^1.0.1
#  flip_panel: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - imagens/banner.jpeg
      - imagens/ic_launcher.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
